(define (domain searching)
 (:requirements :strips :typing)
 (:types agent location)
 (:predicates (checked ?l - location) (looked-left ?a - agent) (looked-right ?a - agent))
 (:action look-at
  :parameters (?a - agent ?l - location)
  :precondition (and)
  :effect (checked ?l))
 (:action look-left :parameters (?a - agent)
  :precondition (and) :effect (looked-left ?a))
 (:action look-right :parameters (?a - agent)
  :precondition (and) :effect (looked-right ?a)))
